### ISSUE TITLE
prod-init is failing when processing with camel-quarkus 3.2.0

### ISSUE THREAD

**Issue by zhfeng** [l2x6/cq-maven-plugin#265]
It throws the following error
```
[INFO] Error stacktraces are turned on.
[INFO] Scanning for projects...
[INFO] BuildTimeEventSpy is registered.
[INFO] 
[INFO] ---------------< org.apache.camel.quarkus:camel-quarkus >---------------
[INFO] Building Camel Quarkus 3.2.0
[INFO] --------------------------------[ pom ]---------------------------------
[INFO] 
[INFO] --- cq-prod-maven-plugin:4.4.2:prod-init (default-cli) @ camel-quarkus ---
[INFO] Adding to pom.xml: camel-community.version property
[INFO] Adding to pom.xml: camel-quarkus-community.version property
[INFO] Adding to pom.xml: quarkus-community.version property
[INFO] Adding to pom.xml: quarkiverse-cxf-community.version property
[INFO] Adding to pom.xml: graalvm-community.version property
[INFO] Adding to pom.xml: grpc-community.version property
[INFO] Adding to pom.xml: protobuf-community.version property
[INFO] Setting camel-quarkus.extension.finder.strict = false in pom.xml
[INFO] Upgrading in pom.xml: cq-plugin.version 4.3.0 -> 4.4.2
[INFO] Removing from pom.xml: docs module
[INFO] Adding to pom.xml: product module
[INFO] Setting version in pom.xml: camel-buildtools ${camel.version} -> ${camel-community.version}
[INFO] Adding to pom.xml: org.l2x6.cq:cq-prod-maven-plugin:${cq-plugin.version}
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  2.478 s
[INFO] Finished at: 2023-08-29T15:11:37+08:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.l2x6.cq:cq-prod-maven-plugin:4.4.2:prod-init (default-cli) on project camel-quarkus: Execution default-cli of goal org.l2x6.cq:cq-prod-maven-plugin:4.4.2:prod-init failed: No value present -> [Help 1]

org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.l2x6.cq:cq-prod-maven-plugin:4.4.2:prod-init (default-cli) on project camel-quarkus: Execution default-cli of goal org.l2x6.cq:cq-prod-maven-plugin:4.4.2:prod-init failed: No value present
	at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute2(MojoExecutor.java:375)
	at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute(MojoExecutor.java:351)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:215)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:171)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:163)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:56)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:298)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:192)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:105)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:960)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:293)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:196)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:282)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:225)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:406)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:347)
Caused by: org.apache.maven.plugin.PluginExecutionException: Execution default-cli of goal org.l2x6.cq:cq-prod-maven-plugin:4.4.2:prod-init failed: No value present
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:148)
	at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute2(MojoExecutor.java:370)
	... 22 common frames omitted
Caused by: java.util.NoSuchElementException: No value present
	at java.base/java.util.Optional.get(Optional.java:143)
	at org.l2x6.cq.maven.prod.ProdInitMojo.lambda$execute$14(ProdInitMojo.java:388)
	at org.l2x6.pom.tuner.PomTransformer.transform(PomTransformer.java:154)
	at org.l2x6.pom.tuner.PomTransformer.transform(PomTransformer.java:129)
	at org.l2x6.pom.tuner.PomTransformer.transform(PomTransformer.java:118)
	at org.l2x6.cq.maven.prod.ProdInitMojo.execute(ProdInitMojo.java:379)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)
	... 23 common frames omitted
[ERROR] 
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginExecutionException
```

It seem releated to https://github.com/apache/camel-quarkus/commit/6e96ceb6a9dec6d46e7c3fb6ff9743edc3033149#diff-2bd046434f86b6d92e0cbba69d5570596319b244a7ba0d4e3cab3ee235e13681 which removes `protobuf-maven-plugin` from `integration-tests/grpc/pom.xml`

I think it needs to remove such a step in `ProdInitMojo.java`.

**Comment by zhfeng** [comment]
Sorry, it has been fixed by https://github.com/l2x6/cq-maven-plugin/commit/635d3edd91a436d41575276735ed3e8f8a3cd957
but I think we need a new release?

**Comment by ppalaga** [comment]
> we need a new release?

Feel free to release, then. The steps are documented here: https://github.com/l2x6/cq-maven-plugin#releasing

**Comment by zhfeng** [comment]
Thanks @ppalaga and these open PRs
- https://github.com/l2x6/cq-maven-plugin/pull/259
- https://github.com/l2x6/cq-maven-plugin/pull/260
- https://github.com/l2x6/cq-maven-plugin/pull/261
- https://github.com/l2x6/cq-maven-plugin/pull/263

can be merged before releasing?

And what about https://github.com/l2x6/cq-maven-plugin/issues/264 ?

**Comment by ppalaga** [comment]
Yes, thanks for noticing. I merged them all

**Comment by ppalaga** [comment]
... and I am reviewing #264

**Comment by ppalaga** [comment]
Oh, I though #265 and #264 were the same issue. Sorry. 
Could you please check if the prod build works for you with the new 4.4 branch that I just pushed? It is the same as main, but has 44f41ae8cbcf59204d9fc3d9e13946b65c1f65b4 omitted. If it works for you, feel free to release 4.4.3 from that branch.

**Comment by zhfeng** [comment]
OK, I will check it. Thanks again for your helping!

**Comment by zhfeng** [comment]
Hi @ppalaga ,  `4.4` branch is working and I'm happy to do a new release of `4.4.3`.
